### ISSUE TITLE
`update_all` raises error when no rows are updated

### ISSUE THREAD

**Issue by rupurt** [elixir-sqlite/ecto_sqlite3#30]
The ecto spec for `Ecto.Repo.Assoc.query` expects a list of rows but currently the `ecto_sqlite3` adapter returns `nil` when there were no rows updated from the query.

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/assoc.ex#L10

This results in the following error:

```bash
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Exqlite.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, List, Date.Range, Stream, Range, Map, HashDict, GenEvent.Stream, MapSet, HashSet, IO.Stream, Function, File.Stream
```

**Comment by rupurt** [comment]
Added example test case in https://github.com/elixir-sqlite/ecto_sqlite3/pull/31

**Comment by kevinlang** [comment]
https://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3

> The second element is nil by default unless a select is supplied in the update query. Note, however, not all databases support returning data from UPDATEs.

Nice find! An immediate workaround is to not have any `select` in the query, if that works for you.

I believe the issue is in `Exqlite`. Specifically around the `maybe_rows` logic where we _always_ map `[]` to `nil` for `rows`. Around `lib/exqlite/connection.ex:474`.

I tried removing that `maybe_rows` logic but then hit another issue in Ecto and the return results it expects:
```
** (CaseClauseError) no case clause matching: {:ok, %Exqlite.Result{columns: [], command: :execute, num_rows: 1, rows: []}}
    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:786: Ecto.Adapters.SQL.struct/10
    (ecto 3.6.1) lib/ecto/repo/schema.ex:717: Ecto.Repo.Schema.apply/4
    (ecto 3.6.1) lib/ecto/repo/schema.ex:342: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:296: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
    (ecto_sql 3.6.0) lib/ecto/migrator.ex:310: Ecto.Migrator.run_maybe_in_transaction/4
    (elixir 1.11.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by kevinlang** [comment]
Maybe this is the test we need to make passing in order to fix this behavior?

https://github.com/elixir-sqlite/exqlite/pull/146

**Comment by kevinlang** [comment]
I think we need to detect the difference between "returning specified" and "no returning specified", and return `[]` or `nil` accordingly in those cases. I think if we do that in the NIF (if possible) we can simplify some of our Elixir code too, in Exqlite.

See what Postgrex does:
`lib/postgrex/protocol.ex:2818`
```
    rows = if is_nil(cols) and rows == [] and command != :copy, do: nil, else: rows
```

Can we do something similar in SQLite3? I.e., do we get a non-empty list of columns in the RETURNING case that we can use as a signal as to whether the query could _possibly_ return something?
