### ISSUE TITLE
Can’t checkout connection from Ecto Sandbox after restarting application in tests

### ISSUE THREAD

**Issue by rupurt** [elixir-sqlite/ecto_sqlite3#35]
Howdy,

I'm trying to figure out the best way to test my Elixir application using Ecto + a supervision tree. During the test the supervision tree dynamically starts processes which causes test pollution. The tests pass when run individually.

My initial thought was that I should restart the application, but that causes the following problem when trying to checkout a new connection from the Ecto sandbox.

```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10999ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
     
       1. Ensuring your database is available and that you can connect to it
       2. Tracking down slow queries and making sure they are running fast enough
       3. Increasing the pool_size (albeit it increases resource consumption)
       4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
     
     See DBConnection.start_link/2 for more information
```

I get the following error in my logs

```
17:44:49.279 [error] Exqlite.Connection (#PID<0.950.0>) failed to connect: ** (Exqlite.Error) got :database_open_failed while retrieving Exception.message/1 for %Exqlite.Error{message: :database_open_failed, statement: nil} (expected a string)
```

This is my custom data case template

```elixir
defmodule Tai.TestSupport.DataCase do
  @moduledoc """
  This module defines the setup for tests requiring
  access to the application's data layer.

  You may define functions here to be used as helpers in
  your tests.

  Finally, if the test case interacts with the database,
  we enable the SQL sandbox, so changes done to the database
  are reverted at the end of every test. If you are using
  PostgreSQL, you can even run database tests asynchronously
  by setting `use Tai.DataCase, async: true`, although
  this option is not recommended for other databases.
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      alias Tai.NewOrders.OrderRepo
      alias Tai.TestSupport.Mocks

      import Ecto
      import Ecto.Changeset
      import Ecto.Query
      import Tai.TestSupport.DataCase
      import Tai.TestSupport.Mock
      import Tai.TestSupport.Factories.NewOrderSubmissionFactory
      import Tai.TestSupport.Factories.NewOrderFactory
      import Tai.TestSupport.Factories.OrderTransitionFactory
      import Tai.TestSupport.Factories.FailedOrderTransitionFactory
    end
  end

  setup tags do
    Application.stop(:tai)
    {:ok, _} = Application.ensure_all_started(:tai)

    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Tai.NewOrders.OrderRepo)

    unless tags[:async] do
      Ecto.Adapters.SQL.Sandbox.mode(Tai.NewOrders.OrderRepo, {:shared, self()})
    end

    start_supervised!(Tai.TestSupport.Mocks.Server)

    :ok
  end

  @doc """
  A helper that transforms changeset errors into a map of messages.

      assert {:error, changeset} = Accounts.create_user(%{password: "short"})
      assert "password is too short" in errors_on(changeset).password
      assert %{password: ["password is too short"]} = errors_on(changeset)

  """
  def errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {message, opts} ->
      Regex.replace(~r"%{(\w+)}", message, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
  end
end
```

**Comment by warmwaffles** [comment]
What are the configs for the repo in the test environment?

**Comment by rupurt** [comment]
```elixir
config :tai, ecto_repos: [Tai.NewOrders.OrderRepo]

config :tai, Tai.NewOrders.OrderRepo,
  database: "./apps/tai/priv/orders_#{Mix.env()}.db",
  show_sensitive_data_on_connection_error: true,
  pool: Ecto.Adapters.SQL.Sandbox
```

**Comment by warmwaffles** [comment]
This project right? https://github.com/fremantle-industries/tai 

Do you have a branch where I can replicate this?

**Comment by rupurt** [comment]
That's the one. This is the branch `orders-ecto-repo-restart-application`

https://github.com/fremantle-industries/tai/commit/9369caa8bf34432489592ccf337e3fd5cbc884dc includes a description and a `mix test` command to replicate the issue

**Comment by warmwaffles** [comment]
Can you help me bootstrap this app for my local machine?

I just cloned, and checked out that sha and ran

```
mix deps.get
MIX_ENV=test mix test --trace apps/tai/test/tai/iex/commands/new_orders_test.exs
```

```
* (Mix) Could not start application tai: exited in: Tai.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) can't fetch value for key `:test_venue_adapters` of application `:tai`, can not resolve key BINANCE_API_KEY value via adapter Elixir.Confex.Adapters.FileFromSystemEnvironment
            (confex 3.5.0) lib/confex.ex:248: Confex.resolve_and_update_env/3
            (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
            (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
            (tai 0.0.65) lib/tai/application.ex:5: Tai.Application.start/2
            (kernel 8.0) application_master.erl:347: :application_master.start_supervisor/3
            (kernel 8.0) application_master.erl:329: :application_master.start_the_app/5
            (kernel 8.0) application_master.erl:315: :application_master.start_it_new/7
```

**Comment by rupurt** [comment]
Add a `.env` file and source it with this

```
export GDAX_API_PASSPHRASE=$PWD/secrets/ci/gdax_api_passphrase
export GDAX_API_KEY=$PWD/secrets/ci/gdax_api_key
export GDAX_API_SECRET=$PWD/secrets/ci/gdax_api_secret

export BINANCE_API_KEY=$PWD/secrets/ci/binance_api_key
export BINANCE_API_SECRET=$PWD/secrets/ci/binance_api_secret

export BITMEX_API_KEY=$PWD/secrets/ci/bitmex_api_key
export BITMEX_API_SECRET=$PWD/secrets/ci/bitmex_api_secret

export OKEX_API_KEY=$PWD/secrets/ci/okex_api_key
export OKEX_API_SECRET=$PWD/secrets/ci/okex_api_secret
export OKEX_API_PASSPHRASE=$PWD/secrets/ci/okex_api_passphrase
```

**Comment by warmwaffles** [comment]
Excellent, just had to add the following to that

```
export DERIBIT_CLIENT_ID=$PWD/secrets/ci/deribit_client_id
export DERIBIT_CLIENT_SECRET=$PWD/secrets/ci/deribit_client_secret

export FTX_API_KEY=$PWD/secrets/ci/ftx_api_key
export FTX_API_SECRET=$PWD/secrets/ci/ftx_api_secret
```

**Comment by rupurt** [comment]
:raised_hands: thanks for looking into this @warmwaffles :beers:

**Comment by warmwaffles** [comment]
@rupurt so I am looking at the database and the schema only has the migrations table and doesn't have any migrations / tables applied.

```shell
MIX_ENV=test mix ecto.drop -r Tai.NewOrders.OrderRepo
MIX_ENV=test mix ecto.create -r Tai.NewOrders.OrderRepo
MIX_ENV=test mix ecto.migrate -r Tai.NewOrders.OrderRepo
```

And then the error results in the following.

```
Tai.IEx.Commands.NewOrdersTest [test/tai/iex/commands/new_orders_test.exs]
  * test shows an empty table when there are no orders (126.8ms) [L#75]

  1) test shows an empty table when there are no orders (Tai.IEx.Commands.NewOrdersTest)
     apps/tai/test/tai/iex/commands/new_orders_test.exs:75
     ** (exit) exited in: GenServer.call(Tai.Commander, {:new_orders, nil, []}, 5000)
         ** (EXIT) an exception was raised:
             ** (Exqlite.Error) no such table: orders
     SELECT o0.client_id, o0.close, o0.credential, o0.cumulative_qty, o0.last_received_at, o0.last_venue_timestamp, o0.leaves_qty, o0.post_only, o0.price, o0.product_symbol, o0.product_type, o0.qty, o0.side, o0.status, o0.time_in_force, o0.type, o0.venue, o0.venue_order_id, o0.venue_product_symbol, o0.inserted_at, o0.updated_at FROM orders AS o0 ORDER BY o0.inserted_at LIMIT ? OFFSET ?
                 (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
                 (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5
                 (ecto 3.6.1) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
                 (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
                 (tai 0.0.65) lib/tai/commander.ex:121: Tai.Commander.handle_call/3
                 (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
                 (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
                 (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     code: assert capture_io(&Tai.IEx.new_orders/0) == """
     stacktrace:
       (elixir 1.11.3) lib/gen_server.ex:1027: GenServer.call/3
       (tai 0.0.65) lib/tai/iex/commands/new_orders.ex:28: Tai.IEx.Commands.NewOrders.new_orders/0
       (ex_unit 1.11.3) lib/ex_unit/capture_io.ex:191: ExUnit.CaptureIO.do_capture_gl/2
       (ex_unit 1.11.3) lib/ex_unit/capture_io.ex:149: ExUnit.CaptureIO.do_capture_io/3
       test/tai/iex/commands/new_orders_test.exs:76: (test)

  * test shows items in ascending order from when they were enqueued (229.3ms) [L#24]

  2) test shows items in ascending order from when they were enqueued (Tai.IEx.Commands.NewOrdersTest)
     apps/tai/test/tai/iex/commands/new_orders_test.exs:24
     ** (Exqlite.Error) no such table: orders
     INSERT INTO orders (close,credential,cumulative_qty,leaves_qty,post_only,price,product_symbol,product_type,qty,side,status,time_in_force,type,venue,venue_order_id,venue_product_symbol,client_id,inserted_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
     code: insert_spot_order(%{
     stacktrace:
       (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.6.1) lib/ecto/repo/schema.ex:717: Ecto.Repo.Schema.apply/4
       (ecto 3.6.1) lib/ecto/repo/schema.ex:342: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       test/tai/iex/commands/new_orders_test.exs:30: (test)



Finished in 0.5 seconds
2 tests, 2 failures
```

**Comment by rupurt** [comment]
You probably need to generate the migrations

```
mix tai.gen.migration 
```

**Comment by warmwaffles** [comment]
Okay so I am still getting a `no such table` error BUT, I did tweak the configs a bit. I am not running into the checkout issue. I've seen that happen if the directory does not exist or the database file is not created.

```elixir
config :tai,
  Tai.NewOrders.OrderRepo,
  database: "./apps/tai/priv/orders_#{Mix.env()}.db",
  journal_mode: :wal,
  cache_size: -64000,
  temp_store: :memory,
  pool_size: 5,
  chunk_size: 100
```

**Comment by rupurt** [comment]
Thanks for the kind words :blush: Hit me up any time if you want to dive deeper on it.

> Okay so I am still getting a no such table error BUT, I did tweak the configs a bit. I am not running into the checkout issue. I've seen that happen if the directory does not exist or the database file is not created.

Hmmm, not sure why I'm getting different results. But based on your suggestion that the database file isn't created I changed the path lookup to the following and it now works correctly!

```elixir
config :tai, Tai.NewOrders.OrderRepo,
  database:
    [__DIR__, "../apps/tai/priv/tai/orders_#{Mix.env()}.db"]
    |> Path.join()
```

**Comment by warmwaffles** [comment]
I'm going to leave this ticket open for a little while. If you figure anything out let me know.

**Comment by rupurt** [comment]
Closing this as I haven't needed to revisit the problem with the absolute path fix
