### ISSUE TITLE
create unique_index?

### ISSUE THREAD

**Issue by rdtq** [elixir-sqlite/ecto_sqlite3#37]
I'm trying to create unique_index on existing table field, but there's an error
Migration file:
```
defmodule App.Repo.Migrations.PayloadUniqueConstraint do
  use Ecto.Migration

  def change do
    create unique_index(:payloads, [:name])
  end
end
```

Error:
```bash
$ mix ecto.migrate

18:56:37.589 [info]  == Running 20210614154426 App.Repo.Migrations.PayloadUniqueConstraint.change/0 forward

18:56:37.595 [info]  create index payloads_name_index
** (Exqlite.Error) UNIQUE constraint failed: payloads.name
CREATE UNIQUE INDEX payloads_name_index ON payloads (name)
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:836: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.6.1) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.6.1) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.12.0) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.6.1) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib 3.15.1) timer.erl:166: :timer.tc/1
    (ecto_sql 3.6.1) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.6.1) lib/ecto/migrator.ex:324: Ecto.Migrator.attempt/8
    (ecto_sql 3.6.1) lib/ecto/migrator.ex:251: anonymous fn/5 in Ecto.Migrator.do_up/5
    (ecto_sql 3.6.1) lib/ecto/migrator.ex:295: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
    (ecto_sql 3.6.1) lib/ecto/migrator.ex:310: Ecto.Migrator.run_maybe_in_transaction/4
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by rdtq** [comment]
Never mind, error was because of pre-existing records violating constraint :)
